name: Update LeetCode Stats

on:
  push:
    paths:
      - stats.json
  schedule:
    - cron: '0 1 * * *'  # optional: daily at 1AM UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: python update_readme.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Update LeetCode stats" || echo "No changes"
          git push
